import type { DashboardData } from "./types";

/** Demo data aligned with staging E2E runs and Stitch dashboard mock. */
export const demoDashboard: DashboardData = {
  product: "Groww",
  environment: "development",
  currentIsoWeek: "2026-W24",
  isoWeekPolicy: "Monday before 9am IST → previous complete week",
  kpis: {
    lastRunStatus: "completed",
    lastRunIsoWeek: "2026-W24",
    reviewsAnalyzed: 884,
    themesFound: 5,
    nextScheduledRun: "Mon 09:00 IST",
  },
  alert: {
    severity: "warning",
    message: "1 partial run — Doc delivered, Gmail failed. Retry available.",
    isoWeek: "2026-W22",
  },
  runs: [
    {
      isoWeek: "2026-W24",
      status: "completed",
      reviewCount: 884,
      themeCount: 5,
      durationSeconds: 48,
      runId: "2026-W24-20260610T132614Z-5c9efbc2",
      docUrl: "https://docs.google.com/document/d/1ArysoTqwaheaUsz4QLHdm5HKOvkkAe_aDwbVnz43ZfA/edit",
      docStatus: "open",
      emailStatus: "draft",
    },
    {
      isoWeek: "2026-W23",
      status: "skipped",
      reviewCount: null,
      themeCount: null,
      durationSeconds: null,
      runId: null,
      docUrl: null,
      docStatus: "none",
      emailStatus: "none",
    },
    {
      isoWeek: "2026-W22",
      status: "partial",
      reviewCount: 872,
      themeCount: 5,
      durationSeconds: 41,
      runId: "2026-W22-20260603T091500Z-a1b2c3d4",
      docUrl: "https://docs.google.com/document/d/1ArysoTqwaheaUsz4QLHdm5HKOvkkAe_aDwbVnz43ZfA/edit",
      docStatus: "open",
      emailStatus: "failed",
      errorMessage: "Gmail MCP unavailable",
    },
    {
      isoWeek: "2026-W21",
      status: "completed",
      reviewCount: 901,
      themeCount: 5,
      durationSeconds: 52,
      runId: "2026-W21-20260527T033012Z-e5f6a7b8",
      docUrl: "https://docs.google.com/document/d/1ArysoTqwaheaUsz4QLHdm5HKOvkkAe_aDwbVnz43ZfA/edit",
      docStatus: "open",
      emailStatus: "sent",
    },
    {
      isoWeek: "2026-W20",
      status: "failed",
      reviewCount: null,
      themeCount: null,
      durationSeconds: 12,
      runId: "2026-W20-20260520T033045Z-f9e8d7c6",
      docUrl: null,
      docStatus: "failed",
      emailStatus: "failed",
      errorMessage: "Insufficient reviews: 18 < 20",
    },
  ],
  schedulerNote: "GitHub Actions · Mon 09:00 IST · .github/workflows/weekly-pulse.yml",
};
